name: Deploy

on:
  push:
    branches: [main]

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: echo "Build du projet..."
      - name: Placeholder for deploy
        run: echo "Étape de déploiement à venir..."